AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  PenmanFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Handler: app.main.handler
      CodeUri: .
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: penman-data
          QUEUE_URL: YOUR_SQS_URL
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
